/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: bigint | number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DivisionSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'divisionCode',
    'divisionName',
    'id',
    'status',
    'updatedAt',
  ] as const
  $columns = DivisionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare divisionCode: string
  @column()
  declare divisionName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['accessLevel', 'createdAt', 'id', 'systemId', 'updatedAt', 'userId'] as const
  $columns = RoleSchema.$columns
  @column()
  declare accessLevel: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare systemId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: bigint | number
}

export class SectionSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'divisionId',
    'id',
    'sectionCode',
    'sectionName',
    'status',
    'updatedAt',
  ] as const
  $columns = SectionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare divisionId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare sectionCode: string
  @column()
  declare sectionName: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SystemSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'status', 'systemName', 'updatedAt'] as const
  $columns = SystemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: string
  @column()
  declare systemName: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'fname',
    'id',
    'lname',
    'mname',
    'password',
    'position',
    'sectionId',
    'status',
    'updatedAt',
    'username',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fname: string
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare lname: string
  @column()
  declare mname: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare position: string
  @column()
  declare sectionId: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}
