/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Divisions: () => import('#controllers/divisions_controller'),
  Sections: () => import('#controllers/sections_controller'),
  Users: () => import('#controllers/users_controller'),
  Systems: () => import('#controllers/systems_controller'),
  Roles: () => import('#controllers/roles_controller'),
}
